name = "RayTracer"
uuid = "60dacb86-48ff-11e9-0f01-03ab8794bbc9"
authors = ["Avik Pal <avikpal@iitk.ac.in>"]
version = "0.1.0"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extras]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
